jobs:
  include:
    - stage: warm_cache
      language: node_js
      node_js:
          - 12
          - 14
      script:
        - echo "foo" > foo.txt
      workspaces:
        create:
          name: ws1
          paths:
            - foo.txt
    - stage: use_cache
      workspaces:
        use: ws1
      script:
        - cat foo.txt || true

stages:
  - warm_cache
  - use_cache