language: node_js

jobs:
  include:
    - stage: warm_cache
      script:
        - echo "foo" > foo.txt
      workspaces:
        create:
          name: ws1
          paths:
            - foo.txt
    - stage: use_cache
      workspaces:
        use: ws1
      script:
        - cat foo.txt || true

node_js:
  - "12"
  - "14"

workspaces:
    use: ws1
	
script:
    - cat foo.txt || true

stages:
  - warm_cache
  - use_cache
  - test