language: node_js
node_js:
  - 12
  - 14

script:
  - echo "foo" > foo.txt

deploy:
  skip_cleanup: true
  provider: script
  script: 
    - cat foo.txt || true
  on:
    branch: master
    node_js: 12
