language: node_js
node_js:
    - 12
    - 14

jobs:
    include:
        - stage: Testing
          script: 
              - echo hello > 1.txt
          workspaces:
              create: 
                  name: bundle 
                  paths: .

